apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: test-url
spec:
  template:
    metadata:
      name: test-url
    spec:
     restartPolicy: Never
     containers:
     - name: test-url
       image: registry.access.redhat.com/ubi8-minimal:8.7-1031
       workingDir: /workspace/output
       command: ["/bin/bash", "-c"]
       args: ["curl ${SERVICE}:${PORT}/health/liveliness || exit 1"]
       env:
         - name: SERVICE
           value: {{ .Release.Name }}-service
         - name: PORT
           value: {{ .Values.service.servicePort }}
  backoffLimit: 1